# Generated by Django 4.0 on 2022-01-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('ml_handler', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('related_session', models.IntegerField(default=0)),
                ('model_uploaded', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('local_path', models.CharField(default='', max_length=260)),
                ('global_path', models.CharField(default='', max_length=260)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_handler.mlmodel')),
                ('user', models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('founder', models.CharField(max_length=20, unique=True)),
                ('min_num_of_participants', models.IntegerField()),
                ('max_num_of_participants', models.IntegerField()),
                ('actual_num_of_participants', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('with_test_set', models.BooleanField(default=False)),
                ('test_dataset', models.BinaryField(null=True)),
                ('pricing_plan', models.IntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=0)),
                ('participants', models.ManyToManyField(related_name='participants', to='session_handler.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('participant_uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_handler.participant')),
                ('related_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_handler.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('session_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_models_accuracy_json', models.CharField(max_length=1000, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('global_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_handler.mlmodel')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_handler.sessionresult'),
        ),
    ]
