# Generated by Django 4.0 on 2021-12-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_handler', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_uploaded', models.BooleanField()),
                ('is_owner', models.BooleanField()),
                ('local_path', models.CharField(max_length=260)),
                ('global_path', models.CharField(max_length=260)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_handler.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('session_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_models_accuracy_json', models.CharField(max_length=1000, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('global_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_handler.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('min_num_of_participants', models.IntegerField()),
                ('max_num_of_participants', models.IntegerField()),
                ('actual_num_of_participants', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('creation_date', models.DateField()),
                ('with_test_set', models.BooleanField(default=False)),
                ('test_dataset', models.BinaryField(default=False)),
                ('pricing_plan', models.IntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=0)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_handler.participant')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_handler.sessionresult')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='related_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_handler.session'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
