# Generated by Django 4.0 on 2021-12-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
