# Generated by Django 4.0 on 2022-01-06 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='model_structure',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='parameters_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='session',
            name='parameters_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
    ]
