# Generated by Django 4.0 on 2021-12-21 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0002_alter_session_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='related_session',
            field=models.IntegerField(null=True),
        ),
    ]
