# Generated by Django 4.0 on 2022-01-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_handler', '0002_remove_mlmodel_owner'),
        ('session_handler', '0002_session_model_structure_session_parameters_keys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='related_session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='session',
            name='result',
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_handler.session'),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_handler.session'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_handler.mlmodel'),
        ),
    ]
