# Generated by Django 4.0 on 2022-01-06 17:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0003_remove_participant_related_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='model_uploaded',
            new_name='is_model_uploaded',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='model_structure',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='global_path',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='local_path',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='model',
        ),
        migrations.RemoveField(
            model_name='sessionresult',
            name='global_model',
        ),
        migrations.RemoveField(
            model_name='storagefile',
            name='participant_uploaded',
        ),
        migrations.RemoveField(
            model_name='storagefile',
            name='related_session',
        ),
        migrations.AddField(
            model_name='participant',
            name='local_data_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='weights_uploaded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_handler.storagefile'),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='global_model_accuracy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
