# Generated by Django 4.0 on 2021-12-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0003_session_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='global_path',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='local_path',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='participant',
            name='model_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='related_session',
            field=models.IntegerField(default=0),
        ),
    ]
