# Generated by Django 4.0 on 2022-01-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0004_rename_model_uploaded_participant_is_model_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
    ]
