# Generated by Django 4.0 on 2022-01-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0005_alter_session_test_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('participant_uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_handler.participant')),
                ('related_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_handler.session')),
            ],
        ),
    ]
