# Generated by Django 4.0 on 2022-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0006_session_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='founder',
            field=models.CharField(max_length=20),
        ),
    ]
