# Generated by Django 4.0 on 2022-01-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0007_alter_session_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
