# Generated by Django 4.0 on 2022-01-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0009_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefile',
            name='related_session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='session_handler.session'),
            preserve_default=False,
        ),
    ]
