# Generated by Django 4.0 on 2022-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0009_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='private_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
