# Generated by Django 4.0 on 2022-01-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0010_session_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session_handler.session'),
        ),
    ]
