# Generated by Django 4.0 on 2022-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0010_storagefile_related_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='loss',
            field=models.FloatField(null=True),
        ),
    ]
