# Generated by Django 4.0 on 2022-01-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0012_remove_sessionresult_local_models_accuracy_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionresult',
            name='global_model_accuracy',
        ),
        migrations.RemoveField(
            model_name='sessionresult',
            name='global_model_loss',
        ),
    ]
