# Generated by Django 4.0 on 2022-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0013_remove_sessionresult_global_model_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionresult',
            name='global_model_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='global_model_loss',
            field=models.FloatField(null=True),
        ),
    ]
