# Generated by Django 4.0 on 2022-01-14 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0014_sessionresult_global_model_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default='{}', size=None),
            preserve_default=False,
        ),
    ]
