# Generated by Django 4.0 on 2022-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0015_alter_session_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='private_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
