# Generated by Django 4.0 on 2022-01-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0015_alter_session_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='federated_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='federated_round',
            field=models.IntegerField(default=1),
        ),
    ]
