# Generated by Django 4.0 on 2022-02-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0016_session_federated_round_session_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='private_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
