# Generated by Django 4.0 on 2021-12-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('ml_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('creation_date', models.DateField()),
                ('model_parameters_json', models.CharField(max_length=1000)),
                ('model_type', models.IntegerField(choices=[(0, 'ImageClassification'), (1, 'TextClassification')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
