# Generated by Django 4.0 on 2022-01-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='owner',
        ),
    ]
