# Generated by Django 4.0 on 2021-12-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_parameters_json',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
