# Generated by Django 4.0 on 2022-02-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_handler', '0002_remove_mlmodel_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
